# Generated by Django 5.2.4 on 2025-07-13 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={},
        ),
        migrations.RemoveField(
            model_name='discussionreply',
            name='user',
        ),
        migrations.AddField(
            model_name='discussion',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussionreply',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_replies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussionreply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='core.course'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discussionreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
