# Generated by Django 5.2.4 on 2025-07-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_discussion_options_remove_discussionreply_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('manager', 'Manager')], default='student', max_length=10),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
